import {
  CartItemSchema,
  CouponSchema,
  OrderSchema,
  OrderStatusSchema,
  OrderTrackingSchema,
  OrderTotalsSchema,
  ProductSchema,
  type CartItem,
  type Coupon,
  type Order,
  type OrderStatus,
  type OrderTracking,
  type OrderTotals,
  type Product,
} from "@/lib/schemas"

const sampleProducts = [
  {
    id: 1,
    name: "Headphone JBL T460BT",
    brand: "JBL",
    category: "Áudio",
    price: 125.0,
    originalPrice: 199.99,
    discount: 37,
    rating: 4.5,
    reviews: 2847,
    description:
      "Som poderoso com graves profundos, conexão Bluetooth e design dobrável para levar para qualquer lugar.",
    features: [
      "Som JBL Pure Bass",
      "Até 11 horas de bateria",
      "Conexão Bluetooth",
      "Microfone integrado para chamadas",
      "Design dobrável e leve",
    ],
    colors: [
      { name: "Preto", value: "#1a1a1a" },
      { name: "Branco", value: "#ffffff" },
      { name: "Azul", value: "#1e40af" },
      { name: "Rosa", value: "#ec4899" },
    ],
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
    inStock: true,
    emoji: "🎧",
  },
  {
    id: 2,
    name: "Notebook Ultrafino 14”",
    brand: "byShop",
    category: "Computadores",
    price: 3899.9,
    originalPrice: 4599.9,
    discount: 15,
    rating: 4.6,
    reviews: 912,
    description: "Notebook leve para trabalho e estudo, com boa autonomia e desempenho para o dia a dia.",
    features: ["Tela 14” Full HD", "SSD rápido", "Bateria de longa duração"],
    colors: [{ name: "Cinza", value: "#6b7280" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "💻",
  },
  {
    id: 3,
    name: "Mouse Gamer RGB",
    brand: "byShop",
    category: "Acessórios",
    price: 129.9,
    originalPrice: 179.9,
    discount: 28,
    rating: 4.4,
    reviews: 1530,
    description: "Mouse com DPI ajustável e iluminação RGB.",
    features: ["DPI ajustável", "RGB", "Pegada confortável"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🖱️",
  },
  {
    id: 4,
    name: "Teclado Mecânico",
    brand: "byShop",
    category: "Acessórios",
    price: 249.9,
    originalPrice: 329.9,
    discount: 24,
    rating: 4.7,
    reviews: 2044,
    description: "Teclado mecânico com switches táteis e layout compacto.",
    features: ["Switches táteis", "Layout compacto", "Construção reforçada"],
    colors: [{ name: "Preto", value: "#0b0f19" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "⌨️",
  },
  {
    id: 5,
    name: "Caixa de Som Bluetooth",
    brand: "byShop",
    category: "Áudio",
    price: 199.9,
    originalPrice: 259.9,
    discount: 23,
    rating: 4.3,
    reviews: 801,
    description: "Som portátil com boa autonomia e conexão estável.",
    features: ["Bluetooth", "Bateria durável", "Design compacto"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🔊",
  },
  {
    id: 6,
    name: "Monitor 27” 144Hz",
    brand: "byShop",
    category: "Monitores",
    price: 1399.9,
    originalPrice: 1699.9,
    discount: 18,
    rating: 4.6,
    reviews: 520,
    description: "Monitor gamer com alta taxa de atualização para mais fluidez.",
    features: ["27”", "144Hz", "Baixa latência"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🖥️",
  },
  {
    id: 7,
    name: "Smartphone 128GB",
    brand: "byShop",
    category: "Celulares",
    price: 2499.9,
    originalPrice: 2899.9,
    discount: 13,
    rating: 4.5,
    reviews: 3401,
    description: "Tela brilhante, câmera versátil e desempenho equilibrado.",
    features: ["128GB", "Câmera dupla", "Carregamento rápido"],
    colors: [{ name: "Azul", value: "#1e40af" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "📱",
  },
  {
    id: 8,
    name: "Tablet 10”",
    brand: "byShop",
    category: "Tablets",
    price: 1599.9,
    originalPrice: 1899.9,
    discount: 16,
    rating: 4.4,
    reviews: 1102,
    description: "Ideal para estudos, leitura e streaming.",
    features: ["Tela 10”", "Som estéreo", "Boa bateria"],
    colors: [{ name: "Cinza", value: "#6b7280" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "📟",
  },
  {
    id: 9,
    name: "Webcam Full HD",
    brand: "byShop",
    category: "Acessórios",
    price: 189.9,
    originalPrice: 239.9,
    discount: 21,
    rating: 4.2,
    reviews: 640,
    description: "Webcam para reuniões e aulas, com boa nitidez.",
    features: ["Full HD", "Microfone integrado", "Fácil instalação"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "📷",
  },
  {
    id: 10,
    name: "SSD 1TB NVMe",
    brand: "byShop",
    category: "Componentes",
    price: 499.9,
    originalPrice: 599.9,
    discount: 17,
    rating: 4.8,
    reviews: 980,
    description: "SSD rápido para inicialização e carregamentos mais ágeis.",
    features: ["1TB", "NVMe", "Alta velocidade"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "💾",
  },
  {
    id: 11,
    name: "Headset Gamer",
    brand: "byShop",
    category: "Games",
    price: 299.9,
    originalPrice: 379.9,
    discount: 21,
    rating: 4.3,
    reviews: 744,
    description: "Headset com microfone e conforto para longas sessões.",
    features: ["Microfone", "Confortável", "Som imersivo"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🎮",
  },
  {
    id: 12,
    name: "Controle Sem Fio",
    brand: "byShop",
    category: "Games",
    price: 249.9,
    originalPrice: 299.9,
    discount: 17,
    rating: 4.5,
    reviews: 1150,
    description: "Controle ergonômico com baixa latência.",
    features: ["Sem fio", "Ergonômico", "Boa bateria"],
    colors: [{ name: "Branco", value: "#ffffff" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🕹️",
  },
  {
    id: 13,
    name: "Carregador Turbo 65W",
    brand: "byShop",
    category: "Acessórios",
    price: 149.9,
    originalPrice: 189.9,
    discount: 21,
    rating: 4.6,
    reviews: 910,
    description: "Carregamento rápido compatível com diversos dispositivos.",
    features: ["65W", "USB-C", "Compacto"],
    colors: [{ name: "Branco", value: "#ffffff" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🔌",
  },
  {
    id: 14,
    name: "Power Bank 20.000mAh",
    brand: "byShop",
    category: "Acessórios",
    price: 219.9,
    originalPrice: 269.9,
    discount: 19,
    rating: 4.4,
    reviews: 1333,
    description: "Energia extra para viagens e uso diário.",
    features: ["20.000mAh", "Duas saídas", "Carregamento rápido"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🔋",
  },
  {
    id: 15,
    name: "Câmera de Ação 4K",
    brand: "byShop",
    category: "Câmeras",
    price: 999.9,
    originalPrice: 1199.9,
    discount: 17,
    rating: 4.2,
    reviews: 402,
    description: "Capture suas aventuras com estabilização e boa definição.",
    features: ["4K", "Estabilização", "À prova d’água"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🎥",
  },
  {
    id: 16,
    name: "Cabo USB-C Reforçado",
    brand: "byShop",
    category: "Acessórios",
    price: 39.9,
    originalPrice: 59.9,
    discount: 33,
    rating: 4.6,
    reviews: 2100,
    description: "Cabo resistente para uso diário.",
    features: ["Reforçado", "1,5m", "Alta durabilidade"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🧵",
  },
  {
    id: 17,
    name: "Suporte para Notebook",
    brand: "byShop",
    category: "Acessórios",
    price: 89.9,
    originalPrice: 119.9,
    discount: 25,
    rating: 4.5,
    reviews: 670,
    description: "Melhore ergonomia e ventilação.",
    features: ["Ergonômico", "Leve", "Dobrável"],
    colors: [{ name: "Prata", value: "#d1d5db" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🧩",
  },
  {
    id: 18,
    name: "Smartwatch",
    brand: "byShop",
    category: "Wearables",
    price: 799.9,
    originalPrice: 999.9,
    discount: 20,
    rating: 4.3,
    reviews: 890,
    description: "Acompanhe saúde, notificações e exercícios.",
    features: ["Monitoramento", "Notificações", "Resistente à água"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "⌚",
  },
  {
    id: 19,
    name: "Fone In-Ear",
    brand: "byShop",
    category: "Áudio",
    price: 149.9,
    originalPrice: 199.9,
    discount: 25,
    rating: 4.1,
    reviews: 1200,
    description: "In-ear leve com isolamento passivo.",
    features: ["In-ear", "Leve", "Boa vedação"],
    colors: [{ name: "Branco", value: "#ffffff" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🎶",
  },
  {
    id: 20,
    name: "Roteador Wi‑Fi 6",
    brand: "byShop",
    category: "Rede",
    price: 399.9,
    originalPrice: 499.9,
    discount: 20,
    rating: 4.6,
    reviews: 430,
    description: "Mais velocidade e estabilidade para sua rede doméstica.",
    features: ["Wi‑Fi 6", "Dual band", "Maior alcance"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "📶",
  },
  {
    id: 21,
    name: "Hub USB",
    brand: "byShop",
    category: "Acessórios",
    price: 79.9,
    originalPrice: 99.9,
    discount: 20,
    rating: 4.4,
    reviews: 510,
    description: "Mais portas para seu setup.",
    features: ["4 portas", "Compacto", "Plug and play"],
    colors: [{ name: "Cinza", value: "#6b7280" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🔀",
  },
  {
    id: 22,
    name: "Mochila para Notebook",
    brand: "byShop",
    category: "Acessórios",
    price: 189.9,
    originalPrice: 239.9,
    discount: 21,
    rating: 4.7,
    reviews: 980,
    description: "Proteção e conforto no transporte.",
    features: ["Compartimento acolchoado", "Impermeável", "Ergonômica"],
    colors: [{ name: "Preto", value: "#111827" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🎒",
  },
  {
    id: 23,
    name: "Teclado Sem Fio",
    brand: "byShop",
    category: "Acessórios",
    price: 159.9,
    originalPrice: 199.9,
    discount: 20,
    rating: 4.2,
    reviews: 610,
    description: "Teclado silencioso para escritório.",
    features: ["Sem fio", "Silencioso", "Teclas confortáveis"],
    colors: [{ name: "Branco", value: "#ffffff" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🧾",
  },
  {
    id: 24,
    name: "Mouse Sem Fio",
    brand: "byShop",
    category: "Acessórios",
    price: 89.9,
    originalPrice: 119.9,
    discount: 25,
    rating: 4.3,
    reviews: 1220,
    description: "Mouse compacto para trabalho.",
    features: ["Sem fio", "Leve", "Bateria durável"],
    colors: [{ name: "Cinza", value: "#6b7280" }],
    images: ["/placeholder.svg?height=600&width=600"],
    inStock: true,
    emoji: "🖲️",
  },
] as const

export const products: Product[] = ProductSchema.array().parse(sampleProducts)

export function getProductById(id: number): Product | undefined {
  return products.find((product) => product.id === id)
}

export const allSearchData = [
  {
    category: "Produtos",
    items: [
      { title: "Computadores & Laptops", description: "Encontre notebooks e desktops" },
      { title: "Headphones & Áudio", description: "Fones, caixas de som e mais" },
      { title: "Acessórios para PC", description: "Teclados, mouses e periféricos" },
      { title: "Smartphones", description: "Modelos e marcas populares" },
      { title: "Tablets", description: "Para estudo e entretenimento" },
      { title: "Monitores", description: "Gaming, 4K e ultrawide" },
      { title: "Teclados mecânicos", description: "Switches e layouts variados" },
      { title: "Mouses gamer", description: "DPI alto e ergonomia" },
      { title: "Webcams", description: "Para reuniões e streaming" },
      { title: "Caixas de som", description: "Bluetooth e soundbars" },
    ],
  },
  {
    category: "Categorias",
    items: [
      { title: "Eletrônicos", description: "TVs, celulares e gadgets" },
      { title: "Games & Consoles", description: "Consoles e acessórios" },
      { title: "Casa & Cozinha", description: "Eletros e utilidades" },
      { title: "Moda", description: "Roupas e acessórios" },
      { title: "Esportes", description: "Equipamentos esportivos" },
    ],
  },
  {
    category: "Marcas",
    items: [
      { title: "Apple", description: "iPhone, Mac e acessórios" },
      { title: "Samsung", description: "Galaxy e eletrônicos" },
      { title: "Sony", description: "Áudio e games" },
      { title: "JBL", description: "Áudio portátil" },
      { title: "Logitech", description: "Periféricos" },
    ],
  },
] as const

export const categories = [
  { id: "computadores", title: "Computadores", icon: "💻" },
  { id: "acessorios", title: "Acessórios", icon: "🧩" },
  { id: "audio", title: "Áudio", icon: "🎧" },
  { id: "games", title: "Games", icon: "🎮" },
  { id: "celulares", title: "Celulares", icon: "📱" },
  { id: "monitores", title: "Monitores", icon: "🖥️" },
] as const

export const SAVE10: Coupon = CouponSchema.parse({
  code: "SAVE10",
  title: "10% OFF",
  description: "Cupom de 10% de desconto em itens elegíveis.",
  type: "percent",
  value: 10,
  active: true,
})

export const SAVE20: Coupon = CouponSchema.parse({
  code: "SAVE20",
  title: "20% OFF",
  description: "Cupom de 20% de desconto em itens elegíveis.",
  type: "percent",
  value: 20,
  active: true,
})

export const FREESHIP: Coupon = CouponSchema.parse({
  code: "FREESHIP",
  title: "Frete grátis",
  description: "Remove o custo de frete do pedido.",
  type: "shipping",
  value: 100,
  active: true,
})

export const coupons: Coupon[] = [SAVE10, SAVE20, FREESHIP]

export type CartItemMock = CartItem

export const cartItemsMock: CartItemMock[] = CartItemSchema.array().parse([
  { id: 1, name: "Puma AXIS TR Boot", variant: "Preto / Tamanho 42", price: 125.0, quantity: 1, emoji: "👟" },
  { id: 2, name: "Headphone JBL T460BT", variant: "Preto", price: 199.99, quantity: 1, emoji: "🎧" },
  { id: 3, name: "Caixa de Som Bluetooth", variant: "Branco", price: 79.99, quantity: 1, emoji: "🔊" },
])

export type CustomerReviewMock = {
  id: number
  author: string
  rating: number
  date: string
  title: string
  content: string
  helpful: number
  verified: boolean
}

export const customerReviewsMock: CustomerReviewMock[] = [
  {
    id: 1,
    author: "Maria S.",
    rating: 5,
    date: "10 de janeiro, 2024",
    title: "Excelente custo-benefício!",
    content:
      "Comprei para usar no trabalho e estou muito satisfeita. O som é ótimo, a bateria dura bastante e o conforto é surpreendente. Recomendo!",
    helpful: 45,
    verified: true,
  },
  {
    id: 2,
    author: "Carlos R.",
    rating: 4,
    date: "8 de janeiro, 2024",
    title: "Bom produto, entrega rápida",
    content:
      "O fone atende bem as expectativas. O grave é potente e a conexão bluetooth é estável. Único ponto é que poderia isolar um pouco mais o som externo.",
    helpful: 23,
    verified: true,
  },
  {
    id: 3,
    author: "Ana L.",
    rating: 5,
    date: "5 de janeiro, 2024",
    title: "Melhor fone nessa faixa de preço",
    content:
      "Já tive vários fones bluetooth e esse é de longe o melhor considerando o preço. A qualidade JBL realmente faz diferença.",
    helpful: 67,
    verified: true,
  },
]
